const actionDefine = {
    GET_HOME: 'GET_HOME',
    GET_SONG: 'GET_SONG',
    GET_PLAYSONG: 'GET_PLAYSONG',
    GET_PLAYLIST: 'GET_PLAYLIST',
    GET_STATE_RIGHT: 'GET_STATE_RIGHT',
    IS_LOADPLAYLIST: 'IS_LOADPLAYLIST',
    IS_LOADHOME: 'IS_LOADHOME',
}

export default actionDefine